apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadek
spec:
  rules:
    - host: loadek.k8s.lab.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadek
                port:
                  number: 8080
