---
- name: apply libvirt terraforms
  hosts: localhost

  tasks:
  - name: Apply 00base
    terraform:
      project_path: "00base/envs/{{ tfenv }}"
      state: present
      force_init: true

  - name: Apply 10k8s
    terraform:
      project_path: "20k8s/envs/{{ tfenv }}"
      state: present
      force_init: true

  - name: Apply 20k8splatform
    terraform:
      project_path: "20k8splatform/envs/{{ tfenv }}"
      state: present
      force_init: true

  - name: Apply 04userapps
    terraform:
      project_path: "30userapps/envs/{{ tfenv }}"
      state: present
      force_init: true
