---
- name: apply libvirt terraforms
  hosts: localhost

  tasks:
  - name: Apply 01base 
    terraform:
      project_path: "01base/envs/{{ tfenv }}"
      state: present
      force_init: true
      
  - name: Apply 02k8s
    terraform:
      project_path: "02k8s/envs/{{ tfenv }}"
      state: present
      force_init: true
 
  - name: Apply 03k8splatform 
    terraform:
      project_path: "03k8splatform/envs/{{ tfenv }}"
      state: present
      force_init: true

  - name: Apply 04userapps
    terraform:
      project_path: "04userapps/envs/{{ tfenv }}"
      state: present
      force_init: true