---
- name: apply libvirt terraforms
  hosts: localhost

  tasks:
  - name: Destroy 04userapps
    terraform:
      project_path: "04userapps/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 03k8splatform
    terraform:
      project_path: "03k8splatform/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 02k8s
    terraform:
      project_path: "02k8s/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 01base
    terraform:
      project_path: "01base/envs/{{ tfenv }}"
      state: absent           
