---
- name: apply libvirt terraforms
  hosts: localhost

  tasks:
  - name: Destroy 30userapps
    terraform:
      project_path: "30userapps/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 20k8splatform
    terraform:
      project_path: "20k8splatform/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 10k8s
    terraform:
      project_path: "10k8s/envs/{{ tfenv }}"
      state: absent

  - name: Destroy 00base
    terraform:
      project_path: "00base/envs/{{ tfenv }}"
      state: absent
