apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    
spec:  
  rules:
  - http:
      paths:
      - path: /appone
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80