apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appone
commonLabels:
  env: libvirt1
resources:
  - ../../base

patches:
- target:
    kind: Service
    name: nginx
  path: service-patch.yaml
- target:
    kind: Ingress
    name: nginx
  path: ingress-patch.yaml