name: Check Terraform Formatting
run-name: ${{ github.actor }} is Checking Terrform Formatting 🚀
on: [push]
jobs:
  Run-Terraform-Fmt-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check Terraform Formatting
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
        run: |
          find . -name \*.tf -print0 | xargs -I{} -0 terraform fmt -check {}
